name = "telegram-keyword-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

# 数据库配置 - 主数据库（telegram-keywords-db）
[[d1_databases]]
binding = "DB"
database_name = "telegram-keywords-db"
database_id = "c73f760d-3be7-4895-8fa7-dff7a1fbbd26"

# AI 绑定
[ai]
binding = "AI"

# 环境变量
[vars]
TELEGRAM_BOT_TOKEN = "8759840879:AAEYfyNYXYBgw5mrpoHuLYAxecsN_7SIAts"
ADMIN_TOKEN = "admin"
USER_TOKEN = "user"
